### ISSUE TITLE
numpy.linalg import error when running cooler_density + temporary fix

### ISSUE THREAD

**Issue by laramiemckenna** [mrvollger/StainedGlass#45]
Hey there, ever since the parallelization update, I've been able to run StainedGlass on some especially large genomes and that has been such a game changer, thank you! Unfortunately, I'm coming across this error when running cooler_density. My solve was to go into env.yaml and change the `numpy` version specification from `numpy<1.20` to `numpy>=1.22.4` and then it ran smoothly. I hope this helps! 

**Command Run:**
```
snakemake --cores 24 --use-conda --jobs 20 cooler_density --config sample=ChrY fasta=ChrY.fa window=32 cooler_window=100
```

**Error:** 
```
[Tue May 14 11:31:57 2024]
localrule cooler_density_d:
    input: results/contacts_ChrY_32.gz, /cluster/home/lasmith/centromeres/neo/hap1/chromosomes/ChrY/StainedGlass/ChrY.fa.fai
    output: results/ChrY.32.100.density.cool
    log: logs/cooler_density.ChrY.32.100.log
    jobid: 2
    reason: Missing output files: results/ChrY.32.100.density.cool
    wildcards: SM=ChrY, W=32, CW=100
    resources: mem_mb=16096, mem_mib=15351, disk_mb=1962, disk_mib=1872, tmpdir=/tmp, runtime=120, mem=64

Activating conda environment: .snakemake/conda/ca1aab6256c939063ad2dad3ce65ab6e_
/cluster/home/lasmith/centromeres/neo/hap1/chromosomes/ChrY/StainedGlass/.snakemake/conda/ca1aab6256c939063ad2dad3ce65ab6e_/lib/python3.9/site-packages/cooler/api.py:8: UserWarning: A NumPy version >=1.22.4 and <2.3.0 is required for this version of SciPy (detected version 1.19.5)
  from scipy.sparse import coo_matrix
Traceback (most recent call last):
  File "/cluster/home/lasmith/centromeres/neo/hap1/chromosomes/ChrY/StainedGlass/.snakemake/conda/ca1aab6256c939063ad2dad3ce65ab6e_/bin/cooler", line 7, in <module>
    from cooler.cli import cli
  File "/cluster/home/lasmith/centromeres/neo/hap1/chromosomes/ChrY/StainedGlass/.snakemake/conda/ca1aab6256c939063ad2dad3ce65ab6e_/lib/python3.9/site-packages/cooler/__init__.py", line 14, in <module>
    from .api import Cooler, annotate
  File "/cluster/home/lasmith/centromeres/neo/hap1/chromosomes/ChrY/StainedGlass/.snakemake/conda/ca1aab6256c939063ad2dad3ce65ab6e_/lib/python3.9/site-packages/cooler/api.py", line 8, in <module>
    from scipy.sparse import coo_matrix
  File "/cluster/home/lasmith/centromeres/neo/hap1/chromosomes/ChrY/StainedGlass/.snakemake/conda/ca1aab6256c939063ad2dad3ce65ab6e_/lib/python3.9/site-packages/scipy/sparse/__init__.py", line 294, in <module>
    from ._base import *
  File "/cluster/home/lasmith/centromeres/neo/hap1/chromosomes/ChrY/StainedGlass/.snakemake/conda/ca1aab6256c939063ad2dad3ce65ab6e_/lib/python3.9/site-packages/scipy/sparse/_base.py", line 5, in <module>
    from scipy._lib._util import VisibleDeprecationWarning
  File "/cluster/home/lasmith/centromeres/neo/hap1/chromosomes/ChrY/StainedGlass/.snakemake/conda/ca1aab6256c939063ad2dad3ce65ab6e_/lib/python3.9/site-packages/scipy/_lib/_util.py", line 18, in <module>
    from scipy._lib._array_api import array_namespace
  File "/cluster/home/lasmith/centromeres/neo/hap1/chromosomes/ChrY/StainedGlass/.snakemake/conda/ca1aab6256c939063ad2dad3ce65ab6e_/lib/python3.9/site-packages/scipy/_lib/_array_api.py", line 17, in <module>
    from scipy._lib.array_api_compat import (
  File "/cluster/home/lasmith/centromeres/neo/hap1/chromosomes/ChrY/StainedGlass/.snakemake/conda/ca1aab6256c939063ad2dad3ce65ab6e_/lib/python3.9/site-packages/scipy/_lib/array_api_compat/numpy/__init__.py", line 16, in <module>
    __import__(__package__ + '.linalg')
  File "/cluster/home/lasmith/centromeres/neo/hap1/chromosomes/ChrY/StainedGlass/.snakemake/conda/ca1aab6256c939063ad2dad3ce65ab6e_/lib/python3.9/site-packages/scipy/_lib/array_api_compat/numpy/linalg.py", line 2, in <module>
    from numpy.linalg import __all__ as linalg_all
ImportError: cannot import name '__all__' from 'numpy.linalg' (/cluster/home/lasmith/centromeres/neo/hap1/chromosomes/ChrY/StainedGlass/.snakemake/conda/ca1aab6256c939063ad2dad3ce65ab6e_/lib/python3.9/site-packages/numpy/linalg/__init__.py)
[Tue May 14 11:31:59 2024]
Error in rule cooler_density_d:
    jobid: 2
    input: results/contacts_ChrY_32.gz, /cluster/home/lasmith/centromeres/neo/hap1/chromosomes/ChrY/StainedGlass/ChrY.fa.fai
    output: results/ChrY.32.100.density.cool
    log: logs/cooler_density.ChrY.32.100.log (check log file(s) for error details)
    conda-env: /cluster/home/lasmith/centromeres/neo/hap1/chromosomes/ChrY/StainedGlass/.snakemake/conda/ca1aab6256c939063ad2dad3ce65ab6e_
    shell:

	cooler cload pairs                 -c1 1 -p1 2 -c2 4 -p2 5                 --chunksize 50000000000                 /cluster/home/lasmith/centromeres/neo/hap1/chromosomes/ChrY/StainedGlass/ChrY.fa.fai:100                 --zero-based                 results/contacts_ChrY_32$

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Logfile logs/cooler_density.ChrY.32.100.log not found.

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-05-14T113004.423661.snakemake.log
WorkflowError:
At least one job did not complete successfully.
```

**Comment by mrvollger** [comment]
Thanks for the report!

Can you share the specific versions of cooler, pandas, and numpy that you env installed? I am going to start locking things to specific versions instead of ranges.

**Comment by laramiemckenna** [comment]
Absolutely! Here's the output of `conda list` for the environment used during the successful fun: 

```
conda activate /cluster/home/lasmith/centromeres/neo/hap1/chromosomes/ChrY/StainedGlass/.snakemake/conda/4018f50b65bd0a625849ad987adee327_

conda list

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
aws-c-auth                0.7.20               h5f1c8d9_0    conda-forge
aws-c-cal                 0.6.12               h2ba76a8_0    conda-forge
aws-c-common              0.9.17               h4ab18f5_0    conda-forge
aws-c-compression         0.2.18               h36a0aea_4    conda-forge
aws-c-event-stream        0.4.2               h161de36_10    conda-forge
aws-c-http                0.8.1               h63f54a0_13    conda-forge
aws-c-io                  0.14.8               h96d4d28_0    conda-forge
aws-c-mqtt                0.10.4               hcc7299c_2    conda-forge
aws-c-s3                  0.5.8                h10bd90f_3    conda-forge
aws-c-sdkutils            0.1.16               h36a0aea_0    conda-forge
aws-checksums             0.1.18               h36a0aea_4    conda-forge
aws-crt-cpp               0.26.8              h02fd9b4_10    conda-forge
aws-sdk-cpp               1.11.267             h51dfee4_8    conda-forge
bedtools                  2.31.1               hf5e1c6e_1    bioconda
biopython                 1.83            py310h2372a71_0    conda-forge
bokeh                     3.4.1              pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py310hc6cd4ac_1    conda-forge
bwa                       0.7.18               he4a0461_0    bioconda
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.28.1               hd590300_0    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
cloudpickle               3.0.0              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1           py310hd41b1e2_0    conda-forge
cooler                    0.8.11             pyh7cba7a3_2    bioconda
cytoolz                   0.12.3          py310h2372a71_0    conda-forge
dask                      2024.2.1           pyhd8ed1ab_0    conda-forge
dask-core                 2024.2.1           pyhd8ed1ab_1    conda-forge
dill                      0.3.8              pyhd8ed1ab_0    conda-forge
distributed               2024.2.1           pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
fsspec                    2024.3.1           pyhca7485f_0    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
glog                      0.7.0                hed5481d_0    conda-forge
h5py                      3.11.0          nompi_py310h65828d5_100    conda-forge
hdf5                      1.14.3          nompi_h4f84152_101    conda-forge
htslib                    1.20                 h81da01d_0    bioconda
importlib-metadata        7.1.0              pyha770c72_0    conda-forge
importlib_metadata        7.1.0                hd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
k8                        0.2.5                hdcf5f25_4    bioconda
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
lcms2                     2.15                 h7f713cb_2    conda-forge
ld_impl_linux-64          2.40                 h55db66e_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20240116.2      cxx17_h59595ed_0    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libarrow                  16.0.0           hefa796f_1_cpu    conda-forge
libarrow-acero            16.0.0           hac33072_1_cpu    conda-forge
libarrow-dataset          16.0.0           hac33072_1_cpu    conda-forge
libarrow-substrait        16.0.0           h7e0c224_1_cpu    conda-forge
libblas                   3.9.0           22_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           22_linux64_openblas    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.7.1                hca28451_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h77fa898_7    conda-forge
libgfortran-ng            13.2.0               h69a702a_7    conda-forge
libgfortran5              13.2.0               hca663fb_7    conda-forge
libgomp                   13.2.0               h77fa898_7    conda-forge
libgoogle-cloud           2.23.0               h9be4e54_1    conda-forge
libgoogle-cloud-storage   2.23.0               hc7a4891_1    conda-forge
libgrpc                   1.62.2               h15f2491_0    conda-forge
libjpeg-turbo             2.1.5.1              hd590300_1    conda-forge
liblapack                 3.9.0           22_linux64_openblas    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.27          pthreads_h413a1c8_0    conda-forge
libparquet                16.0.0           h6a7eafb_1_cpu    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libprotobuf               4.25.3               h08a7969_0    conda-forge
libre2-11                 2023.09.01           h5a48ba9_2    conda-forge
libsqlite                 3.45.3               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               hc0a3c3a_7    conda-forge
libthrift                 0.19.0               hb90f79a_1    conda-forge
libtiff                   4.6.0                h8b53f26_0    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvmlite                  0.42.0          py310h1b8f574_1    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.3.3           py310h350c4a5_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
markupsafe                2.1.5           py310h2372a71_0    conda-forge
minimap2                  2.18                 h5bf99c6_0    bioconda
msgpack-python            1.0.8           py310h25c7140_0    conda-forge
multiprocess              0.70.16         py310h2372a71_0    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
numba                     0.59.1          py310h7dc5dd1_0    conda-forge
numpy                     1.23.5          py310h53a5b5f_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.3.0                hd590300_0    conda-forge
orc                       2.0.0                h17fec99_1    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pairix                    0.3.8           py310h83093d7_1    bioconda
pandas                    1.5.0           py310h769672d_0    conda-forge
partd                     1.4.2              pyhd8ed1ab_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
pigz                      2.8                  h2797004_0    conda-forge
pillow                    10.0.1          py310h29da1c1_1    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
psutil                    5.9.8           py310h2372a71_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyarrow                   16.0.0          py310h17c5347_0    conda-forge
pyarrow-core              16.0.0          py310h6f79a3a_0_cpu    conda-forge
pyarrow-hotfix            0.6                pyhd8ed1ab_0    conda-forge
pyfaidx                   0.8.1.1            pyhdfd78af_0    bioconda
pysam                     0.22.1          py310h41dec4a_0    bioconda
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.14         hd12c33a_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyvcf3                    1.0.3              pyhdfd78af_0    bioconda
pyyaml                    6.0.1           py310h2372a71_1    conda-forge
re2                       2023.09.01           h7f4b329_2    conda-forge
readline                  8.2                  h8228510_1    conda-forge
s2n                       1.4.13               he19d79f_0    conda-forge
samtools                  1.20                 h50ea8bc_0    bioconda
scipy                     1.13.0          py310h93e2701_1    conda-forge
setuptools                69.5.1             pyhd8ed1ab_0    conda-forge
simplejson                3.19.2          py310h2372a71_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.0                hdb0a2a9_1    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
tblib                     3.0.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
toolz                     0.12.1             pyhd8ed1ab_0    conda-forge
tornado                   6.4             py310h2372a71_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xyzservices               2024.4.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

**Comment by Gon1976** [comment]
I have the same error: 
 snakemake --cores 24 cooler_density --config window=32 cooler_window=100
Using workflow specific profile workflow/profiles/default for setting default command line arguments.
Thanks for using StainedGlass and please remember to cite the tool!
    Mitchell R Vollger, Peter Kerpedjiev, Adam M Phillippy, Evan E Eichler.
            "StainedGlass: Interactive visualization of massive tandem repeat structures with identity heatmaps"
            Bioinformatics, 2022; https://doi.org/10.1093/bioinformatics/btac018

Config file config/config.yaml is extended by additional config specified via the command line.
[INFO] The sequence will be split into 4 batches.
Assuming unrestricted shared filesystem usage.
Building DAG of jobs...
Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please consider to configure strict priorities by executing 'conda config --set channel_priority strict'.
Using shell: /usr/bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Job stats:
job                 count
----------------  -------
cooler_density          1
cooler_density_d        1
cooler_zoomify_d        1
total                   3

Select jobs to execute...
Execute 1 jobs...

[Thu May 23 13:35:32 2024]
localrule cooler_density_d:
    input: results/contacts_Dm25_32.gz, /home/ggreif/StainedGlass/TcDm25_H1.fasta.fai
    output: results/Dm25.32.100.density.cool
    log: logs/cooler_density.Dm25.32.100.log
    jobid: 2
    reason: Missing output files: results/Dm25.32.100.density.cool
    wildcards: SM=Dm25, W=32, CW=100
    resources: mem_mb=16096, mem_mib=15351, disk_mb=1000, disk_mib=954, tmpdir=/tmp, runtime=120, mem=64

Activating conda environment: .snakemake/conda/92fd4fd073b40f84bb5654715f27ce30_
/home/ggreif/StainedGlass/.snakemake/conda/92fd4fd073b40f84bb5654715f27ce30_/lib/python3.9/site-packages/cooler/api.py:8: UserWarning: A NumPy version >=1.22.4 and <2.3.0 is required for this version of SciPy (detected version 1.19.5)
  from scipy.sparse import coo_matrix
Traceback (most recent call last):
  File "/home/ggreif/StainedGlass/.snakemake/conda/92fd4fd073b40f84bb5654715f27ce30_/bin/cooler", line 6, in <module>
    from cooler.cli import cli
  File "/home/ggreif/StainedGlass/.snakemake/conda/92fd4fd073b40f84bb5654715f27ce30_/lib/python3.9/site-packages/cooler/__init__.py", line 14, in <module>
    from .api import Cooler, annotate
  File "/home/ggreif/StainedGlass/.snakemake/conda/92fd4fd073b40f84bb5654715f27ce30_/lib/python3.9/site-packages/cooler/api.py", line 8, in <module>
    from scipy.sparse import coo_matrix
  File "/home/ggreif/StainedGlass/.snakemake/conda/92fd4fd073b40f84bb5654715f27ce30_/lib/python3.9/site-packages/scipy/sparse/__init__.py", line 294, in <module>
    from ._base import *
  File "/home/ggreif/StainedGlass/.snakemake/conda/92fd4fd073b40f84bb5654715f27ce30_/lib/python3.9/site-packages/scipy/sparse/_base.py", line 5, in <module>
    from scipy._lib._util import VisibleDeprecationWarning
  File "/home/ggreif/StainedGlass/.snakemake/conda/92fd4fd073b40f84bb5654715f27ce30_/lib/python3.9/site-packages/scipy/_lib/_util.py", line 18, in <module>
    from scipy._lib._array_api import array_namespace
  File "/home/ggreif/StainedGlass/.snakemake/conda/92fd4fd073b40f84bb5654715f27ce30_/lib/python3.9/site-packages/scipy/_lib/_array_api.py", line 17, in <module>
    from scipy._lib.array_api_compat import (
  File "/home/ggreif/StainedGlass/.snakemake/conda/92fd4fd073b40f84bb5654715f27ce30_/lib/python3.9/site-packages/scipy/_lib/array_api_compat/numpy/__init__.py", line 16, in <module>
    __import__(__package__ + '.linalg')
  File "/home/ggreif/StainedGlass/.snakemake/conda/92fd4fd073b40f84bb5654715f27ce30_/lib/python3.9/site-packages/scipy/_lib/array_api_compat/numpy/linalg.py", line 2, in <module>
    from numpy.linalg import __all__ as linalg_all
ImportError: cannot import name '__all__' from 'numpy.linalg' (/home/ggreif/StainedGlass/.snakemake/conda/92fd4fd073b40f84bb5654715f27ce30_/lib/python3.9/site-packages/numpy/linalg/__init__.py)
[Thu May 23 13:35:32 2024]
Error in rule cooler_density_d:
    jobid: 2
    input: results/contacts_Dm25_32.gz, /home/ggreif/StainedGlass/TcDm25_H1.fasta.fai
    output: results/Dm25.32.100.density.cool
    log: logs/cooler_density.Dm25.32.100.log (check log file(s) for error details)
    conda-env: /home/ggreif/StainedGlass/.snakemake/conda/92fd4fd073b40f84bb5654715f27ce30_
    shell:

        cooler cload pairs                 -c1 1 -p1 2 -c2 4 -p2 5                 --chunksize 50000000000                 /home/ggreif/StainedGlass/TcDm25_H1.fasta.fai:100                 --zero-based                 results/contacts_Dm25_32.gz results/Dm25.32.100.density.cool

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Logfile logs/cooler_density.Dm25.32.100.log not found.

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-05-23T133531.849068.snakemake.log
WorkflowError:
At least one job did not complete successfully. 

My conda list:
conda list
# packages in environment at /home/ggreif/miniconda3/envs/snakemake:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
amply                     0.1.6              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argparse-dataclass        2.0.0              pyhd8ed1ab_0    conda-forge
attmap                    0.13.2             pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
brotli-python             1.1.0           py312h30efb56_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
coin-or-cbc               2.10.10              h9002f0b_0    conda-forge
coin-or-cgl               0.60.7               h516709c_0    conda-forge
coin-or-clp               1.17.8               h1ee7a9c_0    conda-forge
coin-or-osi               0.108.10             haf5fa05_0    conda-forge
coin-or-utils             2.11.11              hee58242_0    conda-forge
coincbc                   2.10.10           0_metapackage    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda-inject              1.3.1              pyhd8ed1ab_0    conda-forge
configargparse            1.7                pyhd8ed1ab_0    conda-forge
connection_pool           0.0.3              pyhd3deb0d_0    conda-forge
datrie                    0.8.2           py312h98912ed_7    conda-forge
docutils                  0.21.2             pyhd8ed1ab_0    conda-forge
dpath                     2.1.6              pyha770c72_0    conda-forge
eido                      0.2.2              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
gitdb                     4.0.11             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.43             pyhd8ed1ab_0    conda-forge
humanfriendly             10.0               pyhd8ed1ab_6    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
immutables                0.20            py312h98912ed_1    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jsonschema                4.22.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py312h7900ff3_0    conda-forge
ld_impl_linux-64          2.40                 h55db66e_0    conda-forge
libblas                   3.9.0           22_linux64_openblas    conda-forge
libcblas                  3.9.0           22_linux64_openblas    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h77fa898_7    conda-forge
libgfortran-ng            13.2.0               h69a702a_7    conda-forge
libgfortran5              13.2.0               hca663fb_7    conda-forge
libgomp                   13.2.0               h77fa898_7    conda-forge
liblapack                 3.9.0           22_linux64_openblas    conda-forge
liblapacke                3.9.0           22_linux64_openblas    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.27          pthreads_h413a1c8_0    conda-forge
libsqlite                 3.45.3               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               hc0a3c3a_7    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
logmuse                   0.2.6              pyh8c360ce_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5           py312h98912ed_0    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
numpy                     1.26.4          py312heda63a1_0    conda-forge
openssl                   3.3.0                h4ab18f5_3    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py312h1d6d2e6_1    conda-forge
peppy                     0.40.1             pyhd8ed1ab_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
plac                      1.4.3              pyhd8ed1ab_0    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
psutil                    5.9.8           py312h98912ed_0    conda-forge
pulp                      2.8.0           py312h7900ff3_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    8.2.1              pyhd8ed1ab_0    conda-forge
python                    3.12.3          hab00c5b_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.19.1             pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py312h98912ed_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
requests                  2.32.2             pyhd8ed1ab_0    conda-forge
reretry                   0.11.8             pyhd8ed1ab_0    conda-forge
rich                      13.7.1             pyhd8ed1ab_0    conda-forge
rpds-py                   0.18.1          py312h4413252_0    conda-forge
setuptools                70.0.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
slack-sdk                 3.27.2             pyha770c72_0    conda-forge
slack_sdk                 3.27.2               hd8ed1ab_0    conda-forge
smart_open                7.0.4              pyhd8ed1ab_0    conda-forge
smmap                     5.0.0              pyhd8ed1ab_0    conda-forge
snakemake                 8.11.3               hdfd78af_0    bioconda
snakemake-interface-common 1.17.2             pyhdfd78af_0    bioconda
snakemake-interface-executor-plugins 9.1.1              pyhdfd78af_0    bioconda
snakemake-interface-report-plugins 1.0.0              pyhdfd78af_0    bioconda
snakemake-interface-storage-plugins 3.2.2              pyhdfd78af_0    bioconda
snakemake-minimal         8.11.3             pyhdfd78af_0    bioconda
stopit                    1.1.2                      py_0    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
throttler                 1.2.2              pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toposort                  1.10               pyhd8ed1ab_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
typing_extensions         4.11.0             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
ubiquerg                  0.7.0              pyhd8ed1ab_0    conda-forge
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
veracitools               0.1.3                      py_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
wrapt                     1.16.0          py312h98912ed_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yte                       1.5.4              pyha770c72_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
