### ISSUE TITLE
Syntax error in Snakefile

### ISSUE THREAD

**Issue by pilleh** [mrvollger/StainedGlass#6]
Hi,
Such a great tool which I would like to try out with my data. I followed all the installation instructions, but I get the following error when I try to run the pipeline ('snakemake --use-conda --cores 24' -n or 'snakemake --use-conda --cores 24'):

SyntaxError in line 14 of /StainedGlass/workflow/Snakefile:
invalid syntax. Perhaps you forgot a comma? (Snakefile, line 14)

I've uploaded the Snakefile. Just wondering if this is something I can very easily fix?

Many thanks!

[Snakefile.txt](https://github.com/mrvollger/StainedGlass/files/7596799/Snakefile.txt)

**Comment by mrvollger** [comment]
hmm, looks like snakedeploy is incorrectly formatting the snakemake. Unfortunately I don't have much control over this since I do not maintain snakedeploy. To avoid this issue can you download using git instead of snakedeploy.
e.g. 
```
git clone https://github.com/mrvollger/StainedGlass.git
```
And then in the cloned StainedGlass dir you should be able to run your command without errors. 

Let me know how it goes.

**Comment by mrvollger** [comment]
Also made an issue with snakedeploy if you want to track that for the future. 
https://github.com/snakemake/snakedeploy/issues/22

**Comment by pilleh** [comment]
Many thanks, I was able to run it in the cloned StainedGlass dir as you suggested.

**Comment by mrvollger** [comment]
Great. I am going to leave this open until the PR to fix snakedeploy is merged just so others can see.

**Comment by mrvollger** [comment]
This is now fixed in snakedeploy.
