### ISSUE TITLE
heatmap

### ISSUE THREAD

**Issue by duhuipeng** [mrvollger/StainedGlass#9]
Dear author
I am using the bed file generated by snakemake to run your aln_plot.R
But NOW I have a problem,It's my fasta file, just the centromere sequence of each chromosome, with 10kbp of N between each chromosome,But I generated the bed file to use the R runtime, and it came out as follows:
![image](https://user-images.githubusercontent.com/58722433/145680634-377d46a2-9d33-472f-b9c8-b2878aa6c6ea.png)
I'm trying to figure out the range of each of my centromeres by 10kbp of N,(as follow)
![image](https://user-images.githubusercontent.com/58722433/145680722-cde99b43-08f6-44e0-9223-c08a2b1d001f.png)
But I can't get out of this interval of N,I want to know how can I modify this R code to get the picture as above
my code as follow :
/home/miniconda3/envs/r403/bin/Rscript workflow/scripts/aln_plot.R -b results/***_CENTRA.100000.10000.bed -t 90 -p ***CENTRA
Looking forward to your response

Thanks
huipeng Du

**Comment by mrvollger** [comment]
Currently the only way to get this kind of figure is in the square from (instead of the triangle one) e.g.
![image](https://user-images.githubusercontent.com/6935283/145731693-e7dfaa72-af46-4fa5-84cb-50728d646997.png)

I will consider adding this functionality, but what you have shown in your second image is not something that is currently made by the tool and must have been annotation added on afterwards with something like adobe illustrator.

Best,
Mitchell

**Comment by duhuipeng** [comment]
Dear author

I wanted to be able to have this kind of broken boundary between the centromere of different chromosomes, rather than the centromere sequence of all chromosomes being together and not separated, but I used a 10Kbp N boundary between each chromosome, as if the R code was not recognized.
If R code can be realized, could you tell me ?I want to realize it immediately.
Thank you very much

**Comment by mrvollger** [comment]
If you are willing to write the code I am happy to review a pull request. But I don't have time to dedicate to this in the near term.
